#!/usr/bin/env python3
"""Quick probe: which peptide supplier sites return WooCommerce product markup."""
import re
import subprocess
import sys

SITES = [
    ("verified-peptides", "https://verifiedpeptides.com", "/shop"),
    ("particle-peptides", "https://particlepeptides.com", "/shop"),
    ("modern-aminos", "https://modernaminos.com", "/shop"),
    ("paramount-peptides", "https://paramountpeptides.com", "/shop"),
    ("peptide-pros", "https://peptidepros.net", "/shop"),
    ("atomik-labz", "https://atomiklabz.com", "/shop"),
    ("limitless-life", "https://limitlesslifenootropics.com", "/shop"),
    ("koi-peptides", "https://koipeptides.com", "/shop"),
    ("precisely-peptides", "https://www.preciselypeptides.com", "/shop"),
    ("protide-health", "https://protidehealth.com", "/shop"),
    ("peptide-sciences", "https://www.peptidesciences.com", "/shop"),
    ("genesis-peptides", "https://genesispeptides.com", "/shop"),
    ("peptide-haven", "https://peptidehaven.com", "/shop"),
    ("peptide-crafters", "https://peptidecrafters.com", "/shop"),
    ("peptide-lion", "https://peptidelion.com", "/shop"),
    ("peptide-shop-usa", "https://peptideshopusa.com", "/shop"),
    ("peptide-world", "https://peptideworld.com", "/shop"),
    ("peptide-depot", "https://peptidedepot.com", "/shop"),
    ("peptide-express", "https://peptideexpress.com", "/shop"),
    ("peptide-direct", "https://peptidedirect.com", "/shop"),
    ("peptide-hub", "https://peptidehub.com", "/shop"),
    ("peptide-market", "https://peptidemarket.com", "/shop"),
    ("peptide-outlet", "https://peptideoutlet.com", "/shop"),
    ("peptide-plus", "https://peptideplus.com", "/shop"),
    ("peptide-supply", "https://peptidesupply.com", "/shop"),
    ("peptide-zone", "https://peptidezone.com", "/shop"),
    ("peptide-emporium", "https://peptideemporium.com", "/shop"),
    ("peptide-king", "https://peptideking.com", "/shop"),
    ("peptide-mart", "https://peptidemart.com", "/shop"),
    ("peptide-nation", "https://peptidenation.com", "/shop"),
    ("peptide-paradise", "https://peptideparadise.com", "/shop"),
    ("peptide-planet", "https://peptideplanet.com", "/shop"),
    ("peptide-portal", "https://peptideportal.com", "/shop"),
    ("peptide-pro", "https://peptidepro.com", "/shop"),
    ("peptide-solutions", "https://peptidesolutions.com", "/shop"),
    ("peptide-specialists", "https://peptidespecialists.com", "/shop"),
    ("peptide-store", "https://peptidestore.com", "/shop"),
    ("peptide-superstore", "https://peptidesuperstore.com", "/shop"),
    ("peptide-technologies", "https://peptidetechnologies.com", "/shop"),
    ("peptide-universe", "https://peptideuniverse.com", "/shop"),
    ("peptide-vault", "https://peptidevault.com", "/shop"),
    ("peptide-works", "https://peptideworks.com", "/shop"),
    ("peptide-arena", "https://peptidearena.com", "/shop"),
    ("peptide-bazaar", "https://peptidebazaar.com", "/shop"),
    ("peptide-center", "https://peptidecenter.com", "/shop"),
    ("peptide-empire", "https://peptideempire.com", "/shop"),
    ("peptide-forge", "https://peptideforge.com", "/shop"),
    ("peptide-garden", "https://peptidegarden.com", "/shop"),
    ("peptide-harbor", "https://peptideharbor.com", "/shop"),
    ("peptide-heaven", "https://peptideheaven.com", "/shop"),
    ("peptide-island", "https://peptideisland.com", "/shop"),
    ("peptide-kingdom", "https://peptidekingdom.com", "/shop"),
    ("peptide-land", "https://peptideland.com", "/shop"),
    ("peptide-library", "https://peptidelibrary.com", "/shop"),
    ("peptide-life", "https://peptidelife.com", "/shop"),
    ("peptide-lounge", "https://peptidelounge.com", "/shop"),
    ("peptide-mall", "https://peptidemall.com", "/shop"),
    ("peptide-master", "https://peptidemaster.com", "/shop"),
    ("peptide-matrix", "https://peptidematrix.com", "/shop"),
    ("peptide-network", "https://peptidenetwork.com", "/shop"),
    ("peptide-nexus", "https://peptidenexus.com", "/shop"),
    ("peptide-oasis", "https://peptideoasis.com", "/shop"),
    ("peptide-online", "https://peptideonline.com", "/shop"),
    ("peptide-park", "https://peptidepark.com", "/shop"),
    ("peptide-pharm", "https://peptidepharm.com", "/shop"),
    ("peptide-plaza", "https://peptideplaza.com", "/shop"),
    ("peptide-premium", "https://peptidepremium.com", "/shop"),
    ("peptide-prime", "https://peptideprime.com", "/shop"),
    ("peptide-pure", "https://peptidepure.com", "/shop"),
    ("peptide-resource", "https://peptideresource.com", "/shop"),
    ("peptide-route", "https://peptideroute.com", "/shop"),
    ("peptide-sanctuary", "https://peptidesanctuary.com", "/shop"),
    ("peptide-science", "https://peptidescience.com", "/shop"),
    ("peptide-select", "https://peptideselect.com", "/shop"),
    ("peptide-shelf", "https://peptideshelf.com", "/shop"),
    ("peptide-sky", "https://peptidesky.com", "/shop"),
    ("peptide-smart", "https://peptidesmart.com", "/shop"),
    ("peptide-spot", "https://peptidespot.com", "/shop"),
    ("peptide-station", "https://peptidestation.com", "/shop"),
    ("peptide-stock", "https://peptidestock.com", "/shop"),
    ("peptide-stop", "https://peptidestop.com", "/shop"),
    ("peptide-studio", "https://peptidestudio.com", "/shop"),
    ("peptide-supreme", "https://peptidesupreme.com", "/shop"),
    ("peptide-synergy", "https://peptidesynergy.com", "/shop"),
    ("peptide-temple", "https://peptidetemple.com", "/shop"),
    ("peptide-today", "https://peptidetoday.com", "/shop"),
    ("peptide-tower", "https://peptidetower.com", "/shop"),
    ("peptide-town", "https://peptidetown.com", "/shop"),
    ("peptide-trade", "https://peptidetrade.com", "/shop"),
    ("peptide-trail", "https://peptidetrail.com", "/shop"),
    ("peptide-trend", "https://peptidetrend.com", "/shop"),
    ("peptide-trust", "https://peptidetrust.com", "/shop"),
    ("peptide-union", "https://peptideunion.com", "/shop"),
    ("peptide-valley", "https://peptidevalley.com", "/shop"),
    ("peptide-venture", "https://peptideventure.com", "/shop"),
    ("peptide-verse", "https://peptideverse.com", "/shop"),
    ("peptide-village", "https://peptidevillage.com", "/shop"),
    ("peptide-vision", "https://peptidevision.com", "/shop"),
    ("peptide-voyage", "https://peptidevoyage.com", "/shop"),
    ("peptide-way", "https://peptideway.com", "/shop"),
    ("peptide-well", "https://peptidewell.com", "/shop"),
    ("peptide-wonder", "https://peptidewonder.com", "/shop"),
    ("peptide-x", "https://peptidex.com", "/shop"),
    ("peptide-zen", "https://peptidezen.com", "/shop"),
    # additional known/community sites
    ("research-chems", "https://researchchems.ca", "/shop"),
    ("peptide-wholesale", "https://peptidewholesale.com", "/shop"),
    ("peptide-warehouse", "https://peptidewarehouse.com", "/shop"),
    ("peptide-factory", "https://peptidefactory.com", "/shop"),
    ("peptide-bioregulator", "https://peptide-bioregulator.com", "/shop"),
    ("peptide-source", "https://peptidesource.com", "/shop"),
    ("peptide-place", "https://peptideplace.com", "/shop"),
    ("peptide-research", "https://peptideresearch.com", "/shop"),
    ("peptide-labs", "https://peptidelabs.com", "/shop"),
    ("peptide-shop", "https://peptideshop.com", "/shop"),
    ("peptide-vendor", "https://peptidevendor.com", "/shop"),
    ("research-peptides", "https://researchpeptides.com", "/shop"),
    ("peptide-giant", "https://peptidegiant.com", "/shop"),
    ("peptide-palace", "https://peptidepalace.com", "/shop"),
    ("peptide-power", "https://peptidepower.com", "/shop"),
    ("peptide-quest", "https://peptidequest.com", "/shop"),
    ("peptide-realm", "https://peptiderealm.com", "/shop"),
    ("peptide-revolution", "https://peptiderevolution.com", "/shop"),
    ("peptide-therapy", "https://peptidetherapy.com", "/shop"),
    ("peptide-world-usa", "https://peptideworldusa.com", "/shop"),
    ("peptide-xpress", "https://peptidexpress.com", "/shop"),
    ("peptide-yard", "https://peptideyard.com", "/shop"),
    ("peptide-zone-usa", "https://peptidezoneusa.com", "/shop"),
    ("peptide-boutique", "https://peptideboutique.com", "/shop"),
    ("peptide-club", "https://peptideclub.com", "/shop"),
    ("peptide-corner", "https://peptidecorner.com", "/shop"),
    ("peptide-district", "https://peptidedistrict.com", "/shop"),
    ("peptide-domain", "https://peptidedomain.com", "/shop"),
    ("peptide-exchange", "https://peptideexchange.com", "/shop"),
    ("peptide-finder", "https://peptidefinder.com", "/shop"),
    ("peptide-gate", "https://peptidegate.com", "/shop"),
    ("peptide-genius", "https://peptidegenius.com", "/shop"),
    ("peptide-guru", "https://peptideguru.com", "/shop"),
    ("peptide-hall", "https://peptidehall.com", "/shop"),
    ("peptide-hero", "https://peptidehero.com", "/shop"),
    ("peptide-hq", "https://peptidehq.com", "/shop"),
    ("peptide-junction", "https://peptidejunction.com", "/shop"),
    ("peptide-lane", "https://peptidelane.com", "/shop"),
    ("peptide-line", "https://peptideline.com", "/shop"),
    ("peptide-link", "https://peptidelink.com", "/shop"),
    ("peptide-man", "https://peptideman.com", "/shop"),
    ("peptide-max", "https://peptidemax.com", "/shop"),
    ("peptide-mega", "https://peptidemega.com", "/shop"),
    ("peptide-mine", "https://peptidemine.com", "/shop"),
    ("peptide-path", "https://peptidepath.com", "/shop"),
    ("peptide-pavilion", "https://peptidepavilion.com", "/shop"),
    ("peptide-pharmacy", "https://peptidepharmacy.com", "/shop"),
    ("peptide-pioneer", "https://peptidepioneer.com", "/shop"),
    ("peptide-pros-usa", "https://peptideprosusa.com", "/shop"),
    ("peptide-ranch", "https://peptideranch.com", "/shop"),
    ("peptide-rank", "https://peptiderank.com", "/shop"),
    ("peptide-reserve", "https://peptidereserve.com", "/shop"),
    ("peptide-retail", "https://peptideretail.com", "/shop"),
    ("peptide-safari", "https://peptidesafari.com", "/shop"),
    ("peptide-saga", "https://peptidesaga.com", "/shop"),
    ("peptide-ship", "https://peptideship.com", "/shop"),
    ("peptide-show", "https://peptideshow.com", "/shop"),
    ("peptide-society", "https://peptidesociety.com", "/shop"),
    ("peptide-source-usa", "https://peptidesourceusa.com", "/shop"),
    ("peptide-spring", "https://peptidespring.com", "/shop"),
    ("peptide-square", "https://peptidesquare.com", "/shop"),
    ("peptide-style", "https://peptidestyle.com", "/shop"),
    ("peptide-super", "https://peptidesuper.com", "/shop"),
    ("peptide-surge", "https://peptidesurge.com", "/shop"),
    ("peptide-system", "https://peptidesystem.com", "/shop"),
    ("peptide-terminal", "https://peptideterminal.com", "/shop"),
    ("peptide-track", "https://peptidetrack.com", "/shop"),
    ("peptide-trader", "https://peptidetrader.com", "/shop"),
    ("peptide-treasure", "https://peptidetreasure.com", "/shop"),
    ("peptide-tribe", "https://peptidetribe.com", "/shop"),
    ("peptide-united", "https://peptideunited.com", "/shop"),
    ("peptide-value", "https://peptidevalue.com", "/shop"),
    ("peptide-vibe", "https://peptidevibe.com", "/shop"),
    ("peptide-view", "https://peptideview.com", "/shop"),
    ("peptide-vista", "https://peptidevista.com", "/shop"),
    ("peptide-vitality", "https://peptidevitality.com", "/shop"),
    ("peptide-web", "https://peptideweb.com", "/shop"),
    ("peptide-wild", "https://peptidewild.com", "/shop"),
    ("peptide-wind", "https://peptidewind.com", "/shop"),
    ("peptide-works-usa", "https://peptideworksusa.com", "/shop"),
    ("peptide-world-market", "https://peptideworldmarket.com", "/shop"),
    ("peptide-yard-usa", "https://peptideyardusa.com", "/shop"),
    ("peptide-yield", "https://peptideyield.com", "/shop"),
    ("peptide-zone-online", "https://peptidezoneonline.com", "/shop"),
    ("peptide-zone-shop", "https://peptidezoneshop.com", "/shop"),
    ("peptide-zone-store", "https://peptidezonestore.com", "/shop"),
    ("peptide-zone-us", "https://peptidezoneus.com", "/shop"),
    ("peptide-zone-world", "https://peptidezoneworld.com", "/shop"),
    ("peptide-zone-x", "https://peptidezonex.com", "/shop"),
    ("peptide-zone-y", "https://peptidezoney.com", "/shop"),
    ("peptide-zone-z", "https://peptidezonez.com", "/shop"),
]

WC_MARKERS = re.compile(
    r"type-product|woocommerce-loop-product|product_title|woocommerce",
    re.I,
)

def probe(slug, base, path):
    url = f"{base}{path}?s=BPC-157&post_type=product"
    try:
        r = subprocess.run(
            ["curl", "-sL", "-A", "PeptideSearchPro/1.0", "--max-time", "12", "-w", "\n%{http_code}", url],
            capture_output=True,
            text=True,
            timeout=15,
        )
        body, code = r.stdout.rsplit("\n", 1)
        code = int(code.strip()) if code.strip().isdigit() else 0
        products = len(re.findall(r"type-product|woocommerce-loop-product", body, re.I))
        wc = bool(WC_MARKERS.search(body))
        title_m = re.search(r"<title>([^<]{0,100})", body, re.I)
        title = title_m.group(1).strip() if title_m else ""
        return code, products, wc, title
    except Exception as e:
        return 0, 0, False, str(e)

hits = []
for slug, base, path in SITES:
    code, products, wc, title = probe(slug, base, path)
    if code == 200 and products > 0:
        hits.append((slug, base, path, products, title))
        print(f"OK {products:2d} | {slug:22s} | {base}")

print(f"\n--- {len(hits)} scrapeable of {len(SITES)} probed ---", file=sys.stderr)
